### ISSUE TITLE
Cannot turn off the "all" module

### ISSUE THREAD

**Issue by Snownee** [Flemmli97/DebugUtils#1]
### Modloader

Fabric

### Minecraft version

1.20.1 (Dev env.)

### Modloader version

Fabric API 0.91.0+1.20.1

### Mod version

1.0.3

### Description

First of all, thanks for making this mod. It's very useful. However, I have to say that the `debugutils` command is not very easy to enter the module I want. When I accidentally turned on the `minecraft:debug/all`, I tried to turn it off only to find that it didn't work.

### Steps to reproduce

1. `/debugutils minecraft:debug/all`

### Logs

N/A

**Comment by Flemmli97** [comment]
`minecraft:debug/all` cannot be turned on. only off. as turning that on will cause detrimental performance issues
